public enum AnimationState: String, Sendable, CaseIterable {
    case idle
    case walk
    case react
    case sleep
    case drag
    case celebrate
    case stretch
    case yawn
    case lookAround
    case bounce
    case run
    case play
    case roll
    case spin
    case trip
    case dance
    case climb
    case sad
    case love
    case angry
    case shy
    case confused
    case scared
    case eat
    case drink
    case groom
    case sit
    case wave
    case nod
    case headShake
    case sneeze
    case scratch
    case peek
    case gift
    case write
    case phone
    case read
    case chat
    case listen
    case alert
    case think
    case cheer
    case follow
    case hidePeek
    case pickup
    case land
    case type
    case punch
    case somersault
    case blink
    case sniff
    case tailWag
    case pawTap
    case pounce
    case crouch
    case crawl
    case nap
    case dream
    case beg
    case nuzzle
    case surprised
    case blush
    case proud
    case melt
    case sing
    case meditate
    case coffee
    case snack
    case stargaze
    case sparkle
    case slide
    case pawReach
    case guardDuty = "guard"
    case danceCombo
    case somersaultCombo
    case boxingCombo
    case parkourCombo
    case partyCombo
    case trainingCombo
    case joySpinCombo
}
